/**
 */
package org.palladiosimulator.memoryhierarchy.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.command.CommandParameter;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ChildCreationExtenderManager;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.palladiosimulator.memoryhierarchy.MemoryHierarchyFactory;
import org.palladiosimulator.memoryhierarchy.MemoryHierarchyPackage;
import org.palladiosimulator.memoryhierarchy.util.MemoryHierarchyAdapterFactory;
import org.palladiosimulator.pcm.seff.ResourceDemandingBehaviour;
import org.palladiosimulator.pcm.seff.SeffPackage;
import org.palladiosimulator.pcm.seff.seff_reliability.SeffReliabilityPackage;
import org.palladiosimulator.pcm.seff.seff_reliability.util.SeffReliabilitySwitch;
import org.palladiosimulator.pcm.seff.util.SeffSwitch;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The
 * adapters generated by this factory convert EMF adapter notifications into calls to
 * {@link #fireNotifyChanged fireNotifyChanged}. The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * 
 * @generated
 */
public class MemoryHierarchyItemProviderAdapterFactory extends MemoryHierarchyAdapterFactory
        implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This helps manage the child creation extenders. <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(
            MemoryhierarchyEditPlugin.INSTANCE, MemoryHierarchyPackage.eNS_URI);

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType
     * isFactoryForType}. <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object>();

    /**
     * This constructs an instance. <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    public MemoryHierarchyItemProviderAdapterFactory() {
        this.supportedTypes.add(IEditingDomainItemProvider.class);
        this.supportedTypes.add(IStructuredItemContentProvider.class);
        this.supportedTypes.add(ITreeItemContentProvider.class);
        this.supportedTypes.add(IItemLabelProvider.class);
        this.supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyResourceEnvironment} instances.
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected MemoryHierarchyResourceEnvironmentItemProvider memoryHierarchyResourceEnvironmentItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyResourceEnvironment}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter createMemoryHierarchyResourceEnvironmentAdapter() {
        if (this.memoryHierarchyResourceEnvironmentItemProvider == null) {
            this.memoryHierarchyResourceEnvironmentItemProvider = new MemoryHierarchyResourceEnvironmentItemProvider(
                    this);
        }

        return this.memoryHierarchyResourceEnvironmentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.memoryhierarchy.MemoryCache} instances. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * 
     * @generated
     */
    protected MemoryCacheItemProvider memoryCacheItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.memoryhierarchy.MemoryCache}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter createMemoryCacheAdapter() {
        if (this.memoryCacheItemProvider == null) {
            this.memoryCacheItemProvider = new MemoryCacheItemProvider(this);
        }

        return this.memoryCacheItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyLinkingResourceSpecification}
     * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected MemoryHierarchyLinkingResourceSpecificationItemProvider memoryHierarchyLinkingResourceSpecificationItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyLinkingResourceSpecification}.
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter createMemoryHierarchyLinkingResourceSpecificationAdapter() {
        if (this.memoryHierarchyLinkingResourceSpecificationItemProvider == null) {
            this.memoryHierarchyLinkingResourceSpecificationItemProvider = new MemoryHierarchyLinkingResourceSpecificationItemProvider(
                    this);
        }

        return this.memoryHierarchyLinkingResourceSpecificationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyLinkingResource} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected MemoryHierarchyLinkingResourceItemProvider memoryHierarchyLinkingResourceItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyLinkingResource}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter createMemoryHierarchyLinkingResourceAdapter() {
        if (this.memoryHierarchyLinkingResourceItemProvider == null) {
            this.memoryHierarchyLinkingResourceItemProvider = new MemoryHierarchyLinkingResourceItemProvider(this);
        }

        return this.memoryHierarchyLinkingResourceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyContainer} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected MemoryHierarchyContainerItemProvider memoryHierarchyContainerItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyContainer}. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter createMemoryHierarchyContainerAdapter() {
        if (this.memoryHierarchyContainerItemProvider == null) {
            this.memoryHierarchyContainerItemProvider = new MemoryHierarchyContainerItemProvider(this);
        }

        return this.memoryHierarchyContainerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.memoryhierarchy.CacheStartingPoint} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected CacheStartingPointItemProvider cacheStartingPointItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.memoryhierarchy.CacheStartingPoint}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter createCacheStartingPointAdapter() {
        if (this.cacheStartingPointItemProvider == null) {
            this.cacheStartingPointItemProvider = new CacheStartingPointItemProvider(this);
        }

        return this.cacheStartingPointItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.memoryhierarchy.InternalActionWithMemoryResourceCall} instances.
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected InternalActionWithMemoryResourceCallItemProvider internalActionWithMemoryResourceCallItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.memoryhierarchy.InternalActionWithMemoryResourceCall}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter createInternalActionWithMemoryResourceCallAdapter() {
        if (this.internalActionWithMemoryResourceCallItemProvider == null) {
            this.internalActionWithMemoryResourceCallItemProvider = new InternalActionWithMemoryResourceCallItemProvider(
                    this);
        }

        return this.internalActionWithMemoryResourceCallItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyCallAction} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    protected MemoryHierarchyCallActionItemProvider memoryHierarchyCallActionItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyCallAction}. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter createMemoryHierarchyCallActionAdapter() {
        if (this.memoryHierarchyCallActionItemProvider == null) {
            this.memoryHierarchyCallActionItemProvider = new MemoryHierarchyCallActionItemProvider(this);
        }

        return this.memoryHierarchyCallActionItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return this.parentAdapterFactory == null ? this : this.parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public void setParentAdapterFactory(final ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public boolean isFactoryForType(final Object type) {
        return this.supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Adapter adapt(final Notifier notifier, final Object type) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Object adapt(final Object object, final Object type) {
        if (this.isFactoryForType(type)) {
            final Object adapter = super.adapt(object, type);
            if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    public List<IChildCreationExtender> getChildCreationExtenders() {
        return this.childCreationExtenderManager.getChildCreationExtenders();
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public Collection<?> getNewChildDescriptors(final Object object, final EditingDomain editingDomain) {
        return this.childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public ResourceLocator getResourceLocator() {
        return this.childCreationExtenderManager;
    }

    /**
     * This adds a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public void addListener(final INotifyChangedListener notifyChangedListener) {
        this.changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public void removeListener(final INotifyChangedListener notifyChangedListener) {
        this.changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     * 
     * @generated
     */
    @Override
    public void fireNotifyChanged(final Notification notification) {
        this.changeNotifier.fireNotifyChanged(notification);

        if (this.parentAdapterFactory != null) {
            this.parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

    /**
     * This disposes all of the item providers created by this factory. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     * 
     * @generated
     */
    @Override
    public void dispose() {
        if (this.memoryHierarchyResourceEnvironmentItemProvider != null) {
            this.memoryHierarchyResourceEnvironmentItemProvider.dispose();
        }
        if (this.memoryCacheItemProvider != null) {
            this.memoryCacheItemProvider.dispose();
        }
        if (this.memoryHierarchyLinkingResourceSpecificationItemProvider != null) {
            this.memoryHierarchyLinkingResourceSpecificationItemProvider.dispose();
        }
        if (this.memoryHierarchyLinkingResourceItemProvider != null) {
            this.memoryHierarchyLinkingResourceItemProvider.dispose();
        }
        if (this.memoryHierarchyContainerItemProvider != null) {
            this.memoryHierarchyContainerItemProvider.dispose();
        }
        if (this.cacheStartingPointItemProvider != null) {
            this.cacheStartingPointItemProvider.dispose();
        }
        if (this.internalActionWithMemoryResourceCallItemProvider != null) {
            this.internalActionWithMemoryResourceCallItemProvider.dispose();
        }
        if (this.memoryHierarchyCallActionItemProvider != null) {
            this.memoryHierarchyCallActionItemProvider.dispose();
        }
    }

    /**
     * A child creation extender for the {@link SeffPackage}. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     * 
     * @generated
     */
    public static class SeffChildCreationExtender implements IChildCreationExtender {
        /**
         * The switch for creating child descriptors specific to each extended class. <!--
         * begin-user-doc --> <!-- end-user-doc -->
         * 
         * @generated
         */
        protected static class CreationSwitch extends SeffSwitch<Object> {
            /**
             * The child descriptors being populated. <!-- begin-user-doc --> <!-- end-user-doc -->
             * 
             * @generated
             */
            protected List<Object> newChildDescriptors;

            /**
             * The domain in which to create the children. <!-- begin-user-doc --> <!-- end-user-doc
             * -->
             * 
             * @generated
             */
            protected EditingDomain editingDomain;

            /**
             * Creates the a switch for populating child descriptors in the given domain. <!--
             * begin-user-doc --> <!-- end-user-doc -->
             * 
             * @generated
             */
            CreationSwitch(final List<Object> newChildDescriptors, final EditingDomain editingDomain) {
                this.newChildDescriptors = newChildDescriptors;
                this.editingDomain = editingDomain;
            }

            /**
             * <!-- begin-user-doc --> <!-- end-user-doc -->
             * 
             * @generated
             */
            @Override
            public Object caseResourceDemandingBehaviour(final ResourceDemandingBehaviour object) {
                this.newChildDescriptors
                    .add(this.createChildParameter(SeffPackage.Literals.RESOURCE_DEMANDING_BEHAVIOUR__STEPS_BEHAVIOUR,
                            MemoryHierarchyFactory.eINSTANCE.createInternalActionWithMemoryResourceCall()));

                this.newChildDescriptors
                    .add(this.createChildParameter(SeffPackage.Literals.RESOURCE_DEMANDING_BEHAVIOUR__STEPS_BEHAVIOUR,
                            MemoryHierarchyFactory.eINSTANCE.createMemoryHierarchyCallAction()));

                return null;
            }

            /**
             * <!-- begin-user-doc --> <!-- end-user-doc -->
             * 
             * @generated
             */
            protected CommandParameter createChildParameter(final Object feature, final Object child) {
                return new CommandParameter(null, feature, child);
            }

        }

        /**
         * <!-- begin-user-doc --> <!-- end-user-doc -->
         * 
         * @generated
         */
        @Override
        public Collection<Object> getNewChildDescriptors(final Object object, final EditingDomain editingDomain) {
            final ArrayList<Object> result = new ArrayList<Object>();
            new CreationSwitch(result, editingDomain).doSwitch((EObject) object);
            return result;
        }

        /**
         * <!-- begin-user-doc --> <!-- end-user-doc -->
         * 
         * @generated
         */
        @Override
        public ResourceLocator getResourceLocator() {
            return MemoryhierarchyEditPlugin.INSTANCE;
        }
    }

    /**
     * A child creation extender for the {@link SeffReliabilityPackage}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * 
     * @generated
     */
    public static class SeffReliabilityChildCreationExtender implements IChildCreationExtender {
        /**
         * The switch for creating child descriptors specific to each extended class. <!--
         * begin-user-doc --> <!-- end-user-doc -->
         * 
         * @generated
         */
        protected static class CreationSwitch extends SeffReliabilitySwitch<Object> {
            /**
             * The child descriptors being populated. <!-- begin-user-doc --> <!-- end-user-doc -->
             * 
             * @generated
             */
            protected List<Object> newChildDescriptors;

            /**
             * The domain in which to create the children. <!-- begin-user-doc --> <!-- end-user-doc
             * -->
             * 
             * @generated
             */
            protected EditingDomain editingDomain;

            /**
             * Creates the a switch for populating child descriptors in the given domain. <!--
             * begin-user-doc --> <!-- end-user-doc -->
             * 
             * @generated
             */
            CreationSwitch(final List<Object> newChildDescriptors, final EditingDomain editingDomain) {
                this.newChildDescriptors = newChildDescriptors;
                this.editingDomain = editingDomain;
            }

            /**
             * <!-- begin-user-doc --> <!-- end-user-doc -->
             * 
             * @generated
             */
            @Override
            public Object caseResourceDemandingBehaviour(final ResourceDemandingBehaviour object) {
                this.newChildDescriptors
                    .add(this.createChildParameter(SeffPackage.Literals.RESOURCE_DEMANDING_BEHAVIOUR__STEPS_BEHAVIOUR,
                            MemoryHierarchyFactory.eINSTANCE.createInternalActionWithMemoryResourceCall()));

                this.newChildDescriptors
                    .add(this.createChildParameter(SeffPackage.Literals.RESOURCE_DEMANDING_BEHAVIOUR__STEPS_BEHAVIOUR,
                            MemoryHierarchyFactory.eINSTANCE.createMemoryHierarchyCallAction()));

                return null;
            }

            /**
             * <!-- begin-user-doc --> <!-- end-user-doc -->
             * 
             * @generated
             */
            protected CommandParameter createChildParameter(final Object feature, final Object child) {
                return new CommandParameter(null, feature, child);
            }

        }

        /**
         * <!-- begin-user-doc --> <!-- end-user-doc -->
         * 
         * @generated
         */
        @Override
        public Collection<Object> getNewChildDescriptors(final Object object, final EditingDomain editingDomain) {
            final ArrayList<Object> result = new ArrayList<Object>();
            new CreationSwitch(result, editingDomain).doSwitch((EObject) object);
            return result;
        }

        /**
         * <!-- begin-user-doc --> <!-- end-user-doc -->
         * 
         * @generated
         */
        @Override
        public ResourceLocator getResourceLocator() {
            return MemoryhierarchyEditPlugin.INSTANCE;
        }
    }

}
