/**
 *
 * $Id$
 */
package org.palladiosimulator.memoryhierarchy.validation;

import org.palladiosimulator.pcm.core.PCMRandomVariable;
import org.palladiosimulator.pcm.resourcetype.CommunicationLinkResourceType;

/**
 * A sample validator interface for
 * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyLinkingResourceSpecification}. This
 * doesn't really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MemoryHierarchyLinkingResourceSpecificationValidator {
    boolean validate();

    boolean validateCommunicationLinkingResourceType_MemoryHierarchyLinkingResourceSpecification(
            CommunicationLinkResourceType value);

    boolean validateLatency_MemoryHierarchyLinkingResourceSpecification(PCMRandomVariable value);

    boolean validateThroughput_MemoryHierarchyLinkingResourceSpecification(PCMRandomVariable value);

    boolean validateNumberOfReplicas(int value);
}
