/**
 *
 * $Id$
 */
package org.palladiosimulator.memoryhierarchy.validation;

import org.eclipse.emf.common.util.EList;
import org.palladiosimulator.memoryhierarchy.MemoryHierarchyResourceEnvironment;

/**
 * A sample validator interface for
 * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyContainer}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MemoryHierarchyContainerValidator {
    boolean validate();

    boolean validateMemoryHierarchyEnvironment_MemoryHierarchyContainer(
            EList<MemoryHierarchyResourceEnvironment> value);
}
