/**
 *
 * $Id$
 */
package org.palladiosimulator.memoryhierarchy.validation;

import org.eclipse.emf.common.util.EList;
import org.palladiosimulator.memoryhierarchy.CacheStartingPoint;
import org.palladiosimulator.memoryhierarchy.MemoryCache;
import org.palladiosimulator.memoryhierarchy.MemoryHierarchyLinkingResource;

/**
 * A sample validator interface for
 * {@link org.palladiosimulator.memoryhierarchy.MemoryHierarchyResourceEnvironment}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MemoryHierarchyResourceEnvironmentValidator {
    boolean validate();

    boolean validateMemoryCache_MemoryHierarchyResourceEnvironment(EList<MemoryCache> value);

    boolean validateMemoryHierarchyLinkingResource_MemoryHierarchyResourceEnvironment(
            EList<MemoryHierarchyLinkingResource> value);

    boolean validateCpuStartingPoint_MemoryHierarchyResourceEnvironment(CacheStartingPoint value);
}
